services:
  - type: web
    name: skill-team-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: skillbasedteam
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        sync: false
